Linear regression,Ridge and Lasso

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
from sklearn.datasets import fetch_california_housing

In [9]:
dataset=fetch_california_housing()
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [10]:
dataset_df=pd.DataFrame(data=dataset.data,columns=dataset.feature_names)

In [11]:
dataset_df.head(5)
dataset.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

Dividing data into train and test and X and y

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
#to skip to the last feature
#dataset_df[:,:-1]
X=dataset_df
y=pd.DataFrame(data=dataset.target,columns=dataset.target_names)

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,shuffle=True)

In [15]:
X_train.shape,y_train.shape,X_test.shape,y_test.shape

((15480, 8), (15480, 1), (5160, 8), (5160, 1))

In [16]:
#Linear Regression
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()

In [17]:
from sklearn.model_selection import cross_val_score

In [30]:
mse=cross_val_score(lin_reg,X_train,y_train,scoring='neg_mean_squared_error',cv=5)
mean_mse=np.mean(mse)
lin_reg.fit(X_train,y_train)
print(mean_mse)

-1.446688145502288


#Why negative mse

I would like to add here, that this negative error is also helpful in finding best algorithm 
when you are comparing multiple algorithms through GridSearchCV().

This is because after training, GridSearchCV() ranks all the algorithms(estimators) and 
tells you which one is the best. Now when you use an error function, estimator with higher 
score will be ranked higher by sklearn, 
which is not true in the case of MAE (along with MSE and a few others).

In [21]:
print(f"mse:{mse}")
print(f"mean_mse:{mean_mse}")


mse:[-0.50985186 -0.50270071 -5.12422678 -0.57403356 -0.52262783]
mean_mse:-1.446688145502288


In [24]:
#Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [25]:
ridge=Ridge()

In [26]:
params=[{'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}]

In [43]:
ridge_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=10)
ridge_regressor.fit(X_train,y_train)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid=[{'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                    20]}],
             scoring='neg_mean_squared_error')

In [44]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

#If we compare Linear and ridge,both are performing similiarly

{'alpha': 1e-15}
-1.5527067788325155


In [ ]:
est=[lin_reg,ridge]

In [ ]:
best_algo=GridSearchCV(est)

In [32]:
#Lasso Regression
from sklearn.linear_model import Lasso
lasso=Lasso()
params=[{'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}]

In [40]:
lasso_regressor=GridSearchCV(lasso,params,scoring='neg_mean_squared_error',cv=10)

In [41]:
lasso_regressor.fit(X_train,y_train)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.444e+03, tolerance: 1.870e+00
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.470e+03, tolerance: 1.884e+00
  model = cd_fast.enet_coordinate_descent(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.444e+03, toler

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid=[{'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                    20]}],
             scoring='neg_mean_squared_error')

In [42]:
print(lasso_regressor.best_params_)
print(lasso_regressor.best_score_)

{'alpha': 1}
-0.9490988179780899


In [77]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
log=LogisticRegression()


In [78]:
df=load_breast_cancer()

In [79]:
X=pd.DataFrame(df.data,columns=df.feature_names)

In [80]:
X.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [81]:
y=pd.DataFrame(df.target,columns=['Target'])

In [82]:
#To check if balanced dataset
y['Target'].value_counts()

Target
1    357
0    212
Name: count, dtype: int64

In [83]:
#train_test
X_train,X_test,y_train,y_test=train_test_split(X,y,shuffle=True)

In [84]:
params=[{'C':[1,5,10]},{'max_iter':[100,150]}]

In [98]:
log=LogisticRegression(C=100,max_iter=100)
model=GridSearchCV(log,param_grid=params,scoring='f1',cv=5)

In [99]:
model.fit(X_train,y_train)
y_train.shape

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example

(426, 1)

In [100]:
model.best_params_

{'C': 5}

In [101]:
model.best_score_

0.9507575385160717

In [102]:
y_pred=model.predict(X_test)

In [103]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])

In [104]:
from sklearn.metrics import confusion_matrix,classification_report

In [106]:
confusion_matrix(y_test,y_pred)

array([[44,  3],
       [ 4, 92]])

In [110]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.951048951048951